---
- name: Add new user
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    username: 'newuser'
    pswd: '123Qwe!'

  tasks:
    - name: change password for user
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        password: "{{ pswd | password_hash('sha512') }}"
