---
- name: Change password for user
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    pswd: 'pass'
    
  tasks:
    - name: change password for user
      ansible.builtin.user:
        name: user 
        state: present
        password: "{{ pswd | password_hash('sha512') }}"